name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0bd953b8404560299589f7defceefec40c86ae533a47d36ea8fd14cd96546dbd"

[versions]
fabric = "0.14.19"
minecraft = "1.18"
