name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "846fb509abf7f804ad8a7706f6ccd407ca95641e5440c94664bc959a5a469681"

[versions]
fabric = "0.14.19"
minecraft = "1.18"
