name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ebdf8d65b92456856fe00da01cc6bc182b13d002d98b5baeb28a33191262ff3a"

[versions]
minecraft = "1.16.4"
quilt = "0.22.0-beta.1"
