name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "393afb0c8c8a59600339ab66ca66b0b560f33ae8119c09f084e33f91dfe6c186"

[versions]
fabric = "0.14.19"
minecraft = "1.19"
