name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8172b9109ec219f12016eda82e902e2bf594f11617d9f5d3e87afcfd3f94a28f"

[versions]
minecraft = "1.19.3"
quilt = "0.19.0-beta.4"
