name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "35e30fc959ea492e04d6a36717c619fadf02c20d61a7d8051516c8a9019f93ee"

[versions]
minecraft = "1.19.3"
quilt = "0.19.0-beta.6"
