name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4954a200618cd742cd38054b2bc9321f3a3736e63120d435fa0d353b73d403e4"

[versions]
minecraft = "1.19.3"
quilt = "0.22.0-beta.1"
