name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c632a770819dd7e5a7191db94456ad88d7e552c2727ea35e5bd7f72abdd5ebb4"

[versions]
minecraft = "1.19"
quilt = "0.19.0-beta.4"
