name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96d86976e96e04f46a4e771fc6bbff553f49492c5be4c71374637325aafee543"

[versions]
minecraft = "1.19"
quilt = "0.22.0-beta.1"
