name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d89614ef644ce1e0f5e60411b5072a4a39fd6a24c98e49de757ee299113df10f"

[versions]
minecraft = "1.19"
quilt = "0.19.0-beta.6"
