name = "Redstonality"
author = "Wyatt Stanke"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6323b4518830ba5528b51c87d51c95639bffa15797219fd9a4fdada5b07b9a4c"

[versions]
minecraft = "1.19"
quilt = "0.18.6"
