name = "Redstonality"
author = "Wyatt Stanke"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9bbf734a9bba4a98837a2290675b8a878856e3247a5fbf9d9466bf8ef206fbad"

[versions]
minecraft = "1.18.2"
quilt = "0.18.6"
