name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ef9a2cc40a0ca7ce24655289b0b0da12569be85afed6b7b96259c913f683934"

[versions]
minecraft = "1.18.2"
quilt = "0.19.0-beta.6"
