name = "Redstonality"
author = "Wyatt Stanke"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8a0b756ada7ec772dea813e2a978b823547233e6e6c09fe36d0a7d013373b42"

[versions]
fabric = "0.14.18"
minecraft = "1.16.1"
