name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d138083cf0c349c3433150c200cc47536068c51076e2de1745264b299e71751d"

[versions]
fabric = "0.14.19"
minecraft = "1.16.1"
