name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f481458226ec415ca84a67f460588594b2b63cc1a678a062fe9f718830267380"

[versions]
fabric = "0.14.24"
minecraft = "1.16.1"
