name = "Redstonality"
author = "Wyatt Stanke"
version = "0.0.4-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67ffde148b551faee313873f5365b434ee6932df787bd3f898ef64d043b6ad4a"

[versions]
minecraft = "1.19.1"
quilt = "0.18.6"
