name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c62ec337abee2d311508d32bc7f2d1efd7990f4023f8624f8f96a4dd4e088fe5"

[versions]
minecraft = "1.19.1"
quilt = "0.19.0-beta.5"
