name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7ed9f66a0652844298161b20d76321ca5c7c562659b4cb23729ecb37ffb15dd"

[versions]
fabric = "0.14.19"
minecraft = "1.19.1"
