name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40341e448358d9c5c368c6fc6ddbb27708517b69ea18132709c92216ba53941a"

[versions]
fabric = "0.14.19"
minecraft = "1.19.1"
