name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "547ca04d2039c142a98ca6b6dfb68fa68b089bd8bc686a43b73cea1c95654dd2"

[versions]
fabric = "0.14.19"
minecraft = "1.19.1"
