name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c6f11919dfcae83519b0e9c7b85106acb132a8cf5b0aa22ac2f79f0aaa25d56c"

[versions]
fabric = "0.14.19"
minecraft = "1.19.1"
