name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba8f999bdca99d1ed01e4b300fde6b1160f5ed659cb2e922dd9ae592062cc785"

[versions]
fabric = "0.14.19"
minecraft = "1.18.1"
