name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe6cf006618cc3346726fe39d0a4307fc827fa0536dedd78a024997d5dd75383"

[versions]
fabric = "0.14.24"
minecraft = "1.18.1"
