name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6fcc197fa14cd285caf1dafd04b37804ca7b2c5f9cef2c61140aefa6a56c1e3c"

[versions]
fabric = "0.14.19"
minecraft = "1.18.2"
