name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46700af49ec4f89eb428f2edd8acf8c765bdf926b6854330120ea711e727b749"

[versions]
fabric = "0.14.19"
minecraft = "1.18.2"
