name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e9c876158231880fba0ed9e59bbb023fcd030f3f0ee6ece3d27d624fb264f3e"

[versions]
minecraft = "1.16.3"
quilt = "0.19.0-beta.5"
