name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d59fc2136726687d07a24cd4db8754261202b3c547ad14f4a8b79df6c0515670"

[versions]
fabric = "0.14.19"
minecraft = "1.17.1"
