name = "Redstonality"
author = "Wyatt Stanke"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf7d089ec3b5c88fab40a3b270d53be9c0d108037565f0967d48a520637ba398"

[versions]
fabric = "0.14.18"
minecraft = "1.17.1"
