name = "Redstonality"
author = "Wyatt Stanke"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3524e8951cb6bf09948b0c602a8d7043a18350e613d5c8181510f58e6d05bc47"

[versions]
minecraft = "1.16.5"
quilt = "0.18.6"
