name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e11518324fe91b29628e1461f90a39af51fba0ad54b366728db8c2498c795950"

[versions]
fabric = "0.14.19"
minecraft = "1.16.2"
