name = "Redstonality"
author = "Wyatt Stanke"
version = "0.0.4-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f4220d5217664f7af56e809c5207c12d84efdbff653a88b33045372830a7098"

[versions]
fabric = "0.14.18"
minecraft = "1.16.2"
