name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7eb7c1c30b0a1147eec23eeff606a264f8254b3149a31cd1f7bf2bb52ed4c6fa"

[versions]
minecraft = "1.17"
quilt = "0.19.0-beta.5"
