name = "Redstonality"
author = "Wyatt Stanke"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d684eb128b26fd065addf10b644d8994f2d747c84cc51e99fde0040fea6fb394"

[versions]
minecraft = "1.17"
quilt = "0.18.6"
