name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33719172bdddda193c326694fcd5024ad1ec47b070b0a05d9f22b13bee0c8bd8"

[versions]
minecraft = "1.17"
quilt = "0.19.0-beta.4"
