name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "295aea77485e47ead0dbb2990f9dfd46360f64f923b839ecd70f8901c9b06b3b"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
