name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a4b53003ffa3dd1cee3a9eb70ed4c62721caae2a398c9d9eabdb83e93dd8585"

[versions]
fabric = "0.14.24"
minecraft = "1.19.4"
