name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7176c9e79872ae50c4029b55b80982a0a04f223fa7aa8a6f493542010c4ec2be"

[versions]
minecraft = "1.20"
quilt = "0.22.0-beta.1"
