name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d26ca83a2141eab947abff33d8b44bf4f6c5056f0325361a6e489391c38cf524"

[versions]
fabric = "0.14.24"
minecraft = "1.19.3"
