name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd59cf07415415e421aca7cd66888989033f44321adc4a352fb853aa1a8f583d"

[versions]
fabric = "0.14.19"
minecraft = "1.19.3"
