name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d37eb2ee641664464bda2c0d4ced5305383738804c945bd2e8983db25af111d"

[versions]
fabric = "0.14.19"
minecraft = "1.16.5"
