name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2601d868647cde83fb651c01ef44fbde52c24f0a1b77c651b0ed89365d3ae5b"

[versions]
fabric = "0.14.19"
minecraft = "1.16.5"
