name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a488cd9432054290052331e1ed5a08c25e183000099653f6cc5370f1f967e127"

[versions]
fabric = "0.14.24"
minecraft = "1.16.5"
