name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dace153bb8dfe97efd8b7fa76bb66a88c6df401b2130ad7a183e6d978f5156f6"

[versions]
fabric = "0.14.24"
minecraft = "1.16.5"
