name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec7eb03d37df5d3917f1c74fde29d2ce78389236372c468b072792651289af0f"

[versions]
fabric = "0.14.19"
minecraft = "1.16.3"
