name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2bec66e4653b90346799698cf305a2736d9eee8d955eeba9a9e02a87361e7800"

[versions]
fabric = "0.14.24"
minecraft = "1.16.4"
