name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1109b3758bd917149ebca27fc7d725bad6a9c11709a90b5873de090d57f339b3"

[versions]
fabric = "0.14.19"
minecraft = "1.16.4"
