name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d75d45515f4c45256e2e48d66f4efc9a7a6873b5fde4c017ff956e9eaf3fa2c"

[versions]
minecraft = "1.18.1"
quilt = "0.19.0-beta.3"
