name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e0b186aea07724cedd2abbe30126a05057bb043e75313a3e2d05842d3c49670"

[versions]
minecraft = "1.18.1"
quilt = "0.19.0-beta.5"
