name = "Redstonality"
author = "Wyatt Stanke"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5059058094ad95805669b114ab4acfa3b115c152e40c9187e47650306803eaf2"

[versions]
minecraft = "1.16.1"
quilt = "0.18.6"
