name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27a41e0a0a96b44cc397a1fc6c601165ba5d239a2f541ddcbf3d780e0dbe519f"

[versions]
minecraft = "1.16.1"
quilt = "0.19.0-beta.3"
