name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46056267229a4a16fa17966ca8092d53b59b8d4d86c2a0ec57ccfc04b114db95"

[versions]
minecraft = "1.16.1"
quilt = "0.19.0-beta.11"
