name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "930125d4c3cebb82ac694bc84d1b5518395aae10e92508cf2510a0c6708df298"

[versions]
minecraft = "1.19.2"
quilt = "0.22.0-beta.1"
