name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f27ed0a8bbac01b23bcf207938b7197a7e36e93e6083213a042ef523d07c31cf"

[versions]
minecraft = "1.19.2"
quilt = "0.22.0-beta.1"
