name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ac1f0dd8aa9f974b28015e865debb47fee04e1f2dbee21fed12c6ada63fb805"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.4"
