name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9bf5bec21ec968f7ce67fe3d560a993a69639f387478c4a64143bf75af08bf06"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.6"
