name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c384d3aaafcfb07a5d472c210365355ab86f24fadd2a46fc0834335e3184ec97"

[versions]
minecraft = "1.16.2"
quilt = "0.19.0-beta.5"
