name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d27f329d8a894fb8c6e05d7910f5ae0d149ab9649c2f2a0dc78ade69728e045"

[versions]
fabric = "0.14.19"
minecraft = "1.15.2"
