name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65248c6cb825ab4ba312a633388a07ecaeec6809c7e442a873ec515890d68ff7"

[versions]
fabric = "0.14.24"
minecraft = "1.15.2"
