name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c36a3fb437d9a2f7ba4f9e5686b552cad769d5e41ca5ad21c40c04e6f65f462"

[versions]
fabric = "0.14.19"
minecraft = "1.15.2"
