name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0f74da92e916af4aaf944eb1c2d9ef879b7d40fd567fede41f458959e03ff35"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
