name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ff5739798d740568734dfde363aecf331ab7d3c58756d4514e55a97bad09e49"

[versions]
minecraft = "1.19.4"
quilt = "0.19.0-beta.4"
