name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "02d29af351c3f542c3bb0dee568862a385c2dc2f70e08299640a0aa045bbfde8"

[versions]
minecraft = "1.19.4"
quilt = "0.19.0-beta.4"
