name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.2-beta.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45296568303a2ea90d3f6546d77599228a032a418cf387395ebe8d385dc38a28"

[versions]
minecraft = "1.19.4"
quilt = "0.22.0-beta.1"
