name = "Redstonality"
author = "Wyatt Stanke"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5362a3707fc946d28ca1b989dd69cf8ebb031552bd7a036aac62415b0350fe28"

[versions]
minecraft = "1.17.1"
quilt = "0.18.6"
