name = "Redstonality"
author = "Wyatt Stanke"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf7d089ec3b5c88fab40a3b270d53be9c0d108037565f0967d48a520637ba398"

[versions]
minecraft = "1.17.1"
quilt = "0.19.0-beta.3"
