on:
  push:
    paths:
      - .version
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      # Install NodeJS, pnpm, and Go
      - uses: actions/setup-node@v2
        with:
          node-version: latest
        name: Install NodeJS
      - uses: actions/setup-go@v4
        with:
          go-version: latest
        name: Install Go
      - uses: pnpm/action-setup@v2
        with:
          version: latest
        name: Install PNPM
      # Install packwiz
      - run: go install github.com/packwiz/packwiz@latest
        name: Install Packwiz
      # Install pnpm dependencies
      - run: pnpm install
        name: Install dependencies
      # Run scripts
      - run: pnpm build
        name: Build modpack
      # Get version
      - run: echo "VERSION=$(cat .version)" >> $GITHUB_ENV
        name: Get version
      # Release artifacts
      - uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: Fe2hWp6Z
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-unfeature-mode: subset
          modrinth-files: "*.mrpack"
          loaders: quilt
          game-versions: |
            - "1.15.2"
            - "1.16.1"
            - "1.16.2"
            - "1.16.3"
            - "1.16.4"
            - "1.16.5"
            - "1.17"
            - "1.17.1"
            - "1.18"
            - "1.18.1"
            - "1.18.2"
            - "1.19"
            - "1.19.1"
            - "1.19.2"
            - "1.19.3"
            - "1.19.4"
